### ISSUE TITLE
BUG in API 23.0.3.1082 - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by rewiteq** [idea-statica/ideastatica-public#306]
In new version we can't open IdeaStatica model throught API

2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice] method: CreateConProjFromIOM FAILED; iomXmlFileName = 'C:\Users\user\AppData\Local\Temp\OpenModel_g.xml', iomResXmlFileName = 'C:\Users\user\AppData\Local\Temp\OpenModelResult_Z.xml', newIdeaConFileName = '...source\22140_00020_0041_001_2023082095635.ideaCon': System.NullReferenceException: Object reference not set to an instance of an object.
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice] HRESULT: 0x80004003
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice] Source: IdeaStatiCa.OpenModelLink
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice] Stack trace:
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]    at IdeaStatiCa.OpenModelLink.ConnectionDescriptorFactory.SetBeamGeometry(IDesignMember beam, BeamDescriptor& beamDescriptor, ConnectionDescriptor descriptor)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]    at IdeaStatiCa.OpenModelLink.ConnectionDescriptorFactory.AddBeamToDescriptor(ConnectionDescriptor descriptor, IDesignMember beam, BeamData beamOmdata)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]    at IdeaStatiCa.OpenModelLink.ConnectionDescriptorFactory.AddBeams(IContainer`1 beams, OpenModel openModel, ConnectionDescriptor descriptor)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]    at IdeaStatiCa.OpenModelLink.ConnectionDescriptorFactory.Create(OpenModel openModel, Int32 modelIndex, IServiceInputParam serviceInputParam)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]    at IdeaStatiCa.OpenModelLink.OpenModelLink.Import(OpenModel openModel, OpenModelResult openModelResult, Int32 modelIndex, ILibEntityRepository libEntityRepository, CodeEditionData CodeEditionData, IIdeaProject projectCCM, ConDataContract existingDataContract)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]    at IdeaRS.ConnectionService.Service.ConnectionSrv.ImportFromIOM(OpenModel openModel, OpenModelResult openModelResult)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]    at IdeaStatiCa.IOMToConnection.IOMToConnection.ImportInternal(OpenModel openModel, OpenModelResult openModelResult)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]    at (Object , OpenModel , OpenModelResult , String )
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]    at A.ca173bc6555e3790e776cf1a57e43eb49.c4b4a9b57e2cf43911d0d352e2916ab93(Object c80250d4f8c61cfe29a53db57169d717b, OpenModel c80250d4f8c61cfe29a53db57169d717b, OpenModelResult c80250d4f8c61cfe29a53db57169d717b, String c80250d4f8c61cfe29a53db57169d717b)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]    at A.c3ab7b8a6fa8d2e96bc3fe82f335f291a.CreateConProjFromIOM(String iomXmlFileName, String iomResXmlFileName, String newIdeaConFileName)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice] Exception log stack trace:
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at System.String FormatExceptionToString(System.String, System.Exception)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Sentry.SentryId LogWarning(System.String, System.Exception, System.Action`1[IdeaStatiCa.Diagnostics.IIdeaAttachmentAppender])
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Sentry.SentryId c4b4a9b57e2cf43911d0d352e2916ab93(System.Object, System.String, System.Exception, System.Action`1[IdeaStatiCa.Diagnostics.IIdeaAttachmentAppender])
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void CreateConProjFromIOM(System.String, System.String, System.String)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at System.Object SyncInvokeCreateConProjFromIOM(System.Object, System.Object[], System.Object[])
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at System.Object Invoke(System.Object, System.Object[], System.Object[] ByRef)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void InvokeBegin(System.ServiceModel.Dispatcher.MessageRpc ByRef)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void ProcessMessage5(System.ServiceModel.Dispatcher.MessageRpc ByRef)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void ProcessMessage11(System.ServiceModel.Dispatcher.MessageRpc ByRef)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Boolean Process(Boolean)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Boolean DispatchAndReleasePump(System.ServiceModel.Channels.RequestContext, Boolean, System.ServiceModel.OperationContext)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Boolean HandleRequest(System.ServiceModel.Channels.RequestContext, System.ServiceModel.OperationContext)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void AsyncMessagePump(System.IAsyncResult)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void OnAsyncReceiveComplete(System.IAsyncResult)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void UnhandledExceptionFrame(System.IAsyncResult)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void Complete(Boolean)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void OnReceive(System.IAsyncResult)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void UnhandledExceptionFrame(System.IAsyncResult)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void Complete(Boolean)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void OnReceiveComplete(System.Object)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void OnAsyncReadComplete(System.Object)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void UnhandledExceptionFrame(System.IAsyncResult)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void Complete(IntPtr)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void ProtectedInvokeCallback(System.Object, IntPtr)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Int32 ProcessFrameBody(Int32, Byte[], Int32, Int32, System.Net.AsyncProtocolRequest)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void ReadCallback(System.Net.AsyncProtocolRequest)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void CompleteRequest(Int32)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Boolean CheckCompletionBeforeNextRead(Int32)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void ReadCallback(System.IAsyncResult)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void Complete(Boolean)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void OnAsyncIOComplete(System.Object)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void OnAsyncReadComplete(Boolean, Int32, Int32)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void CompleteCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void UnhandledExceptionFrame(UInt32, UInt32, System.Threading.NativeOverlapped*)
2023-08-02 09:56:41.267 +02:00 [Warning] (20444-18) [connections.winservice.connhiddencalculator.connectioncalcservice]   at Void PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

**Comment by nathanlukeIDEA** [comment]
Hi, @rewiteq are you able to provide the XML model? I assume this model could be opened in an earlier version?

**Comment by rewiteq** [comment]
Hi,
It is very strange, but today this issue did not occure. Unfortunately another problem still exists - cutting plates.

**My connection:**
![image](https://github.com/idea-statica/ideastatica-public/assets/115782097/161a50b4-8037-4cd7-8da6-20ec3e961179)

**Result in IdeaStatica**
![image](https://github.com/idea-statica/ideastatica-public/assets/115782097/029980ad-0b6e-47aa-b787-bde66df35389)

**All files**
[22130_00101_0001_001_20230810084227.zip](https://github.com/idea-statica/ideastatica-public/files/12309708/22130_00101_0001_001_20230810084227.zip)

**Comment by rewiteq** [comment]
Hi,
I found the node when IdeaStatica can't create ideacon file. I think this is a problem.

XMl files:
[OpenModel.zip](https://github.com/idea-statica/ideastatica-public/files/12319075/OpenModel.zip)

**Comment by nathanlukeIDEA** [comment]
Hi @rewiteq, I have looked into the bug you have reported in the OpenModel.zip. I do get the same error with your connection. I have reported it, and we will aim to fix this ASAP.

Regarding the parallel plate cut by negative volume (plate), we are still working to fix this.

**Comment by johnnyontheweb** [comment]
Hello,
same error for me:
```
2023-09-01 08:58:35.264 +02:00 [Fatal] (15168-1) [idea.app] Inner exception #1: System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
2023-09-01 08:58:35.264 +02:00 [Fatal] (15168-1) [idea.app] HRESULT: 0x80004003
2023-09-01 08:58:35.264 +02:00 [Fatal] (15168-1) [idea.app] Source: IdeaRS.StucturalModelFromOpenModel
2023-09-01 08:58:35.264 +02:00 [Fatal] (15168-1) [idea.app] Stack trace:
2023-09-01 08:58:35.264 +02:00 [Fatal] (15168-1) [idea.app]    in IdeaRS.StucturalModelFromOpenModel.IDEAOpenFormatModelGenerator.DoImportWork(Object sender, DoWorkEventArgs e)
2023-09-01 08:58:35.264 +02:00 [Fatal] (15168-1) [idea.app]    in IdeaRS.StucturalModelFromOpenModel.IDEAOpenFormatModelGenerator.Import(String workingPath, String sourceFilePath, IMprlManager mprl, Object importSettingParam, IServiceInputParam& serviceInputParam)
2023-09-01 08:58:35.264 +02:00 [Fatal] (15168-1) [idea.app]    in A.c030a93cbc2cc1f64a702a7eced31c4ac.c4b4a9b57e2cf43911d0d352e2916ab93(Object c80250d4f8c61cfe29a53db57169d717b, String c80250d4f8c61cfe29a53db57169d717b, String c80250d4f8c61cfe29a53db57169d717b, IMprlManager c80250d4f8c61cfe29a53db57169d717b, Object c80250d4f8c61cfe29a53db57169d717b, IServiceInputParam& c80250d4f8c61cfe29a53db57169d717b)
2023-09-01 08:58:35.264 +02:00 [Fatal] (15168-1) [idea.app]    in A.c305352e31440514317d95763d9b6b1e8.cc2f67fa0f9d3e0370f59011b1cd80836.c2b6df0551f1a51d4dbf81e3577beecc1()
```

I cannot find what's wrong - I tried to open the attached model with idea.exe, same thing.
[test.zip](https://github.com/idea-statica/ideastatica-public/files/12495346/test.zip)

**Comment by nathanlukeIDEA** [comment]
HI @rewiteq,

The import of your model should now work in the latest version of IDEA StatiCa 23.0.5.1260. 

I will close this bug. I have opened another for the parallel plate cuts. 

Kind regards.
Nathan
