### ISSUE TITLE
[QUESTION] Debugging Error in client.Calculate(connection)

### ISSUE THREAD

**Issue by DevDyl96** [idea-statica/ideastatica-public#567]
I wrote a simple Python script to solve a connection.
I've installed the version 24.0.2.1666. 

```
import clr
import sys
import json
import math
import os

script_dir  = os.path.abspath(os.curdir) 
print(f"script = {script_dir}")

# the name of idea connection project which is used in this script
ideaCon_filename = r"example.ideacon"

# the path to the idea connection installation directory
idea_path = r"C:\\Program Files\IDEA StatiCa\StatiCa 24.0"
connection_project_path = os.path.join(script_dir, ideaCon_filename) 
if not os.path.isfile(connection_project_path):
    print('File not found: ', connection_project_path)


# modify path to be able to load .net assemblies
sys.path.append(idea_path)

# load the assembly IdeaStatiCa.Plugin which is responsible for communication with IdeaStatiCa 
clr.AddReference('IdeaStatiCa.Plugin')
from IdeaStatiCa.Plugin import ConnHiddenClientFactory

# create the instance of the client which communicates with IdeaStatiCa
factory = ConnHiddenClientFactory(idea_path)
client = factory.Create()

# open idea connection project 
client.OpenProject(connection_project_path)

# get information about connections in the project and print them
projectInfo = client.GetProjectInfo()
connections = projectInfo.Connections
for conn in connections:
    print(conn.Identifier)
connection = connections[0].Identifier

# SAVE
client.SaveAsProject(ideaCon_filename.replace('.ideacon', '_API.ideacon'))

# CALCULATE
result = client.Calculate(connection)

# CHECK RESULTS
results_input = client.GetCheckResultsJSON(connection)
print('RESULT INPUT', type(results_input), results_input)
results_json = json.loads(results_input)

#print(json.dumps(results_json, indent=4))

summary_json = results_json['summary']

for item in summary_json:
    print('{0}: {1}, {2}'.format(summary_json[item]['name'], summary_json[item]['checkStatus'] , summary_json[item]['checkValue']))
```

I got:
```
RESULT INPUT <class 'str'> Error
Traceback (most recent call last):
  File "d:\OneDrive\FOLDER_NAME\CHS_model.py", line 106, in <module>
    results_json = json.loads(results_input)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\UserName\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\UserName\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\UserName\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

How can I debug the error? The model works where the calculation is made using the UI.
I also noticed the following facts:

- This script still not works if I used the version 21.1 in the idea_path 
- This scripts works if I use the version 21.1 and the model "T-stub.ideaCon" from the example https://github.com/idea-statica/ideastatica-public/blob/main/examples/api/python/connection/parameter-example/T-stub.py

Thanks

**Comment by DevDyl96** [comment]
I think this error is related to the version of idea statica. Since I've opened a [discussion ](https://github.com/idea-statica/ideastatica-public/discussions/570) about this, I close this issue.
